Global:
  model: pwgan_csmsc
  mode: predict # only support predict
  output: "output"

Predict:
  device: gpu:0
  use_trt: False
  use_mkldnn: False
  cpu_threads: 1
  precision: "fp32"
  batch_size: 1
  model_dir: "pwgan_csmsc"
  input: "./mel.npy"
  lang: zh
  speaker_id: 0
  kernel_option:
    run_mode: paddle