Global:
  model: pwgan_csmsc
  mode: predict # only support predict
  device: gpu:0
  use_trt: False
  use_mkldnn: False
  cpu_threads: 1
  precision: "fp32"
  output: "output"
  model_name: "pwgan_csmsc"
  speaker_dict: None
  lang: zh
  speaker_id: 0

Predict:
  batch_size: 1
  model_dir: "pwgan_csmsc"
  input: "今天天气真不错"
  lang: zh
  speaker_id: 0
  kernel_option:
    run_mode: paddle