Global:
  model: fastspeech2_csmsc
  mode: predict # only support predict
  device: gpu:0
  use_trt: False
  use_mkldnn: False
  cpu_threads: 1
  precision: "fp32"
  output: "output"
  model_name: "fastspeech2_csmsc"
  speaker_dict: None
  lang: zh
  speaker_id: 0

Predict:
  batch_size: 1
  model_dir: "fastspeech2csmsc"
  input: [151, 120, 182, 82, 182, 82, 174, 75, 262, 51, 37, 186, 38, 233]
  lang: zh
  speaker_id: 0
  kernel_option:
    run_mode: paddle