backend: "python"
max_batch_size: 1
input [
  {
    name: "input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
instance_group [
  {
      count: 1
      kind: KIND_GPU
      gpus: [ 0 ]
  }
]
