repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=512]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
              server_env/requirements/.*\.txt
            )$
      - id: trailing-whitespace
        files: \.(md|c|cc|cxx|cpp|cu|h|hpp|hxx|py)$
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        files: \.(md|c|cc|cxx|cpp|cu|h|hpp|hxx|py)$
  - repo: https://github.com/psf/black.git
    rev: 24.4.2
    hooks:
      - id: black
        files: (.*\.(py|pyi|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--resolve-all-configs]
