if(NOT ENABLE_PADDLE_BACKEND)
  if(NOT ENABLE_LITE_BACKEND)
    message(WARNING "Will force to set ENABLE_LITE_BACKEND=ON if ENABLE_PADDLE_BACKEND=OFF when build with KunlunXin.")
    set(ENABLE_LITE_BACKEND ON)      
  endif()
else()
  if(ENABLE_LITE_BACKEND)
    message(WARNING "Will force to set ENABLE_LITE_BACKEND=OFF if ENABLE_PADDLE_BACKEND=ON when build with KunlunXin.")
    set(ENABLE_LITE_BACKEND OFF)      
  endif()
endif()

option(WITH_LITE_XPU_LOG "" ON)
if(NOT ENABLE_PADDLE_BACKEND)
  if(NOT PADDLELITE_URL)
    if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-aarch64-xpu-v213.tgz")
    else ()
      if (WITH_LITE_XPU_LOG)
        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-20230410.tgz")
      else()
        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-without-log-20230303.tgz")
      endif()
    endif()
  endif()
endif()
