pipeline_name: conformer_speech_recognition

SubModules:
  ConformerSpeechRecognition:
    module_name: conformer_speech_recognition
    model_name: chunk_conformer
    model_dir: null
    batch_size: 1
    sample_rate: 16000
    chunk_length: 30
    stride: 10
