name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/build
      - uses: pypa/gh-action-pypi-publish@release/v1
